apiVersion: v1
kind: ConfigMap
metadata:
  name: app3s-config
data:
  TZ: "America/Fortaleza"
  VAULT_ADDR: "http://dti-vault.unilab.edu.br"
  # app3s
  DB_CONNECTION: 'pgsql'
  DB_PORT: '5432'
  # sigaa
  DB_CONNECTION_SIGAA: 'pgsql'
  DB_PORT_SIGAA: '5432'
  DB_DATABASE_SIGAA: 'sistemas_comum'
  MAIL_MAILER: 'smtp'
  MAIL_HOST: 'smtp.noreply.unilab.edu.br'
  MAIL_PORT: '25'
  MAIL_USERNAME: ''
  MAIL_PASSWORD: ''
  MAIL_ENCRYPTION: ''
  # Laravel Default
  APP_NAME: 'app3s-laravel'
  APP_ENV: 'local'
  APP_KEY: 'base64:ZG55aXZleG8yOXk4ZGhkNnVoeWYxMnpjN2VhcHBibG0='
  LOG_CHANNEL: 'stack'
  LOG_DEPRECATIONS_CHANNEL: 'null'
  BROADCAST_DRIVER: 'log'
  CACHE_DRIVER: 'file'
  FILESYSTEM_DISK: 'local'
  QUEUE_CONNECTION: 'sync'
  SESSION_DRIVER: 'file'
  SESSION_LIFETIME: '120'
  MEMCACHED_HOST: '127.0.0.1'
  REDIS_HOST: '127.0.0.1'
  REDIS_PASSWORD: 'null'
  REDIS_PORT: '6379'
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_BUCKET: ''
  AWS_USE_PATH_STYLE_ENDPOINT: 'false'
  PUSHER_APP_ID: ''
  PUSHER_APP_KEY: ''
  PUSHER_APP_SECRET: ''
  PUSHER_HOST: ''
  PUSHER_PORT: '443'
  PUSHER_SCHEME: 'https'
  PUSHER_APP_CLUSTER: 'mt1'
  VITE_PUSHER_APP_KEY: '${PUSHER_APP_KEY}'
  VITE_PUSHER_HOST: '${PUSHER_HOST}'
  VITE_PUSHER_PORT: '${PUSHER_PORT}'
  VITE_PUSHER_SCHEME: '${PUSHER_SCHEME}'
  VITE_PUSHER_APP_CLUSTER: '${PUSHER_APP_CLUSTER}'
  UNILAB_API_ORIGIN: 'https://api.unilab.edu.br/api'
