apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app3s-laravel-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app3s-laravel
  minReplicas: 1
  maxReplicas: 10
