## Como usar:
# docker-compose -f docker-compose.build.yml up --build -d
# docker-compose logs -f
# docker exec -it 3s-dev /bin/bash

## Copias entre container/local
# docker cp 3s-dev:/var/www/html/.env .
# docker cp .env 3s-dev:/var/www/html/

## Obter vendor/autoload
# docker exec -it 3s-dev composer update

## full clean
# docker stop $(docker ps -qa)
# docker rm -f $(docker ps -qa)
# docker rmi -f $(docker images -qa)
# docker volume rm -f $(docker volume ls -q)
# docker network rm $(docker network ls -q)

### Error response from daemon: Get "https://dti-registro.unilab.edu.br/v2/": x509: certificate signed by unknown authority
# sudo -i
# openssl s_client -showcerts -connect dti-registro.unilab.edu.br:443 </dev/null 2>/dev/null|openssl x509 -outform PEM > /tmp/ca.pem
# mkdir -p /etc/docker/certs.d/dti-registro.unilab.edu.br && cp /tmp/ca.pem /etc/docker/certs.d/dti-registro.unilab.edu.br/ca.crt
# service docker restart

## Logar no Registro privado de Images Docker
# docker login https://dti-registro.unilab.edu.br

version: '3.9'

services:
  ###################################
  # Application
  ################################### 
  app-dev-build:
    build:
      context: .
      dockerfile: $PWD/Dockerfile
      target: dev
    image: dti-registro.unilab.edu.br/unilab/app-3s:debug
    container_name: 3s-build
    restart: always
    user: "root:www-data"
    env_file:
      - ./source/.env
    volumes:
      - ./source:/var/www/html
      - /tmp:/var/www/html/public/uploads
    ports:
      - "8082:80"
      - "22:22"
    networks:
      - developer
    depends_on:
      - postgresql

  ###################################
  # PostgreSQL (Optional BD Local)
  ###################################
  postgresql:
    image: postgres:15-bullseye
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./source/.env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - developer

volumes:
  postgresql_data:
    driver: local
    
networks:
 developer:
   name: developer
   driver: bridge