# docker-compose up -d
# docker-compose logs -f
# docker exec -it postgres /bin/bash
# docker cp postgres:/var/lib/postgresql/data/pgdata/pg_hba.conf ./postgres-conf/
# docker cp postgres:/var/lib/postgresql/data/pgdata/postgresql.conf ./postgres-conf/

version: '3.9'
services:
  ###################################
  # PostgreSQL
  ###################################
  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data/pgdata
      - ./postgres-conf/postgresql.conf:/var/lib/postgresql/data/pgdata/postgresql.conf:rw
      - ./postgres-conf/pg_hba.conf:/var/lib/postgresql/data/pgdata/pg_hba.conf:rw
    networks:
      - unilab

  ###################################
  # PgAdmin4 - Tool para PostgreSQL
  ###################################
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_data:/pgadmin4/servers.json
    depends_on:
      - postgresql
    networks:
      - unilab

volumes:
  postgresql_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
 unilab:
   name: unilab
   driver: bridge