apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-3s-laravel
  labels:
    app: app3s-laravel
spec:
  storageClassName: nfs-storage-k8s
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
