apiVersion: v1
kind: ConfigMap
metadata:
  name: app3s-config
data:
  APP_VERSION: 'beta1'
  DB_HOST: 'postgres.postgres-3s.svc.cluster.local'
  DB_DATABASE: '3s-ocorrencias'
  MAIL_FROM_ADDRESS: '3s@noreply.unilab.edu.br'
  MAIL_FROM_NAME: '3S - Sistema de Solicitação de Serviço'
  APP_URL: 'https://3s.unilab.edu.br'
  LOG_LEVEL: 'error'
  APP_DEBUG: 'false'
