apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app3s-prod
resources:
- ../../base
images:
- name: dti-registro.unilab.edu.br/unilab/app-3s:main
  newName: dti-registro.unilab.edu.br/unilab/app-3s
  newTag: latest
patches:
- path: configmap.yaml
- path: deployment.yaml
- path: service.yaml
- path: ingress.yaml
# - path: hpa.yaml
