
# DATABASE POSTGRESQL
# ------------------------------------------------------------------------------------
# -- CONFIGURA USUARIO E SENHA | 3s
# ------------------------------------------------------------------------------------
# create USER "3s" WITH 
#     SUPERUSER
#     LOGIN 
#     CREATEDB
#     CREATEROLE
#     REPLICATION
#     INHERIT
#     CONNECTION LIMIT -1
#     PASSWORD '<PASSWD>';
# COMMENT ON ROLE "3s" IS 'Usuário padrão 3s-ocorrencias.';

# ------------------------------------------------------------------------------------
# -- CRIA DATABASE | 3s-ocorrencias
# ------------------------------------------------------------------------------------
# CREATE DATABASE 3s-ocorrencias
#     WITH
#     OWNER = "3s"
#     ENCODING = 'UTF8'
#     CONNECTION LIMIT = -1
#     TEMPLATE template0;
# COMMENT ON DATABASE 3s-ocorrencias IS 'Dadabase para 3S';
#
# apt install -y iputils-ping telnet curl postgresql-client
# psql -h postgres.3s-postgres.svc.cluster.local -p 5432 -U 3s -d 3s-ocorrencias
# kubectl delete pv $(kubectl get pv | tail -n+2 | awk '$5 == "Released" {print $1}')

---
apiVersion: v1
kind: Namespace
metadata:
  name: 3s-postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: 3s-postgres-secret
  namespace: 3s-postgres
type: Opaque
data:
  PG_PASSWORD: 3s!@#$2023
  PG_PRIMARY_PASSWORD: admin!@#$2023
  PG_ROOT_PASSWORD: postgres!@#$2023

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 3s-postgres-config
  namespace: 3s-postgres
  labels:
    app: postgres
data:
  PG_USER: 3s
  PG_PRIMARY_USER: admin
  PGHOST: /tmp
  PG_MODE: primary # primary, replica, set
  PG_DATABASE: 3s-ocorrencias
  PG_PRIMARY_HOST: postgres.3s-postgres.svc.cluster.local
  PG_PRIMARY_PORT: "5432"
  MODE: postgres
  CRUNCHY_DEBUG: "TRUE"
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-3s-postgres
  namespace: 3s-postgres
  labels:
    app: postgres
spec:
  storageClassName: nfs-storage-k8s
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 3s-postgres-sa
  namespace: 3s-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: 3s-postgres
  labels:
    app: postgres
  annotations:
    metallb.universe.tf/address-pool: int-pool
spec:
  # clusterIP: None
  # type: NodePort
  type: LoadBalancer
  loadBalancerIP: 10.130.0.154
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30100
      name: pgsql
  selector:
    app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: 3s-postgres-primary
  namespace: 3s-postgres
  labels:
    name: 3s-postgres-primary
spec:
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 0
  selector:
    name: 3s-postgres-primary
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: 3s-postgres-replica
  namespace: 3s-postgres
  labels:
    name: 3s-postgres-replica
spec:
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 0
  selector:
    name: 3s-postgres-replica
  type: ClusterIP
  sessionAffinity: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: 3s-postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        name: 3s-postgres-replica
    spec:
      serviceAccount: 3s-postgres-sa
      securityContext:
        fsGroup: 26
      containers:
        - name: postgres
          image: crunchydata/crunchy-postgres:centos8-13.6-4.7.5
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 990m
              memory: 1024Mi
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: pgdata
              mountPath: /pgdata
              readOnly: false
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pvc-3s-postgres