# kubectl logs <POD-NAME> -c 3s -n <NAME-SPACE>
# kubectl logs <POD-NAME> -c postgres -n <NAME-SPACE>
# kubectl logs <POD-NAME> --all-containers -n <NAME-SPACE>

apiVersion: v1
kind: Namespace
metadata:
  name: <APP_NAMESPACE>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: <APP_NAMESPACE>
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: <APP_NAME>
    spec:
      containers:
      - name: <CONTAINER_NAME>
        image: <IMAGE_TAG>
        resources:
          requests:
            cpu: '0.5'
            memory: 128Mi
          limits:
            cpu: 1
            memory: 1Gi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: angular
        volumeMounts:
        - name: tz-america-one
          mountPath: /etc/localtime
        - name: 3s-uplodas
          mountPath: /var/www/html/3s/public/uploads
      volumes:
        - name: tz-america-one
          hostPath:
            path: /usr/share/zoneinfo/America/Fortaleza
            type: File
        - name: 3s-uploads
          emptyDir: {}
  selector:
    matchLabels:
        app: <APP_NAME>
---
apiVersion: v1
kind: Service
metadata:
  name: <APP_NAME>
  namespace: <APP_NAMESPACE>
  labels:
    app: <APP_NAME>
  annotations:
    metallb.universe.tf/address-pool: int-pool
spec:
  selector:
    app: <APP_NAME>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 37389
      targetPort: 37389
      name: ssh
  type: LoadBalancer
  loadBalancerIP: 10.130.0.153
  externalTrafficPolicy: Local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: <APP_NAME>
   namespace: <APP_NAMESPACE>
   annotations:
      haproxy.org/check: enabled
      haproxy.org/forwarded-for: enabled
      haproxy.org/load-balance: roundrobin
      haproxy.org/ssl-redirect: 'true'
      haproxy.org/ssl-redirect-code: '301'
spec:
  rules:
    - host: hello-world-test.unilab.edu.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
               service:
                  name: <APP_NAME>
                  port:
                     number: 80
                     