---
apiVersion: v1
kind: Namespace
metadata:
  name: app-3s
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-3s-config
  namespace: app-3s
  labels:
    app: app-3s
data:
  TZ: 'America/Fortaleza'
  # 3s
  DB_CONNECTION: 'pgsql'
  DB_HOST: 'postgres.postgres-3s.svc.cluster.local'
  DB_PORT: '5432'
  DB_DATABASE: '3s-ocorrencias'
  # sigaa
  DB_CONNECTION_SIGAA: 'pgsql'
  DB_PORT_SIGAA: '5432'
  DB_DATABASE_SIGAA: 'sistemas_comum'
  MAIL_MAILER: 'smtp'
  MAIL_HOST: 'smtp.noreply.unilab.edu.br'
  MAIL_PORT: '25'
  MAIL_USERNAME: ''
  MAIL_PASSWORD: ''
  MAIL_ENCRYPTION: ''
  MAIL_FROM_ADDRESS: '3s@noreply.unilab.edu.br'
  MAIL_FROM_NAME: '3S - Sistema de Solicitacao de Ocorrencias'
  # Laravel Default
  APP_NAME: 'Laravel'
  APP_ENV: 'local'
  APP_KEY: 'base64:ZG55aXZleG8yOXk4ZGhkNnVoeWYxMnpjN2VhcHBibG0='
  APP_DEBUG: 'true'
  APP_URL: 'http://dti-app-test-c1.unilab.edu.br'
  LOG_CHANNEL: 'stack'
  LOG_DEPRECATIONS_CHANNEL: 'null'
  LOG_LEVEL: 'debug'
  BROADCAST_DRIVER: 'log'
  CACHE_DRIVER: 'file'
  FILESYSTEM_DISK: 'local'
  QUEUE_CONNECTION: 'sync'
  SESSION_DRIVER: 'file'
  SESSION_LIFETIME: '120'
  MEMCACHED_HOST: '127.0.0.1'
  REDIS_HOST: '127.0.0.1'
  REDIS_PASSWORD: 'null'
  REDIS_PORT: '6379'
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_BUCKET: ''
  AWS_USE_PATH_STYLE_ENDPOINT: 'false'
  PUSHER_APP_ID: ''
  PUSHER_APP_KEY: ''
  PUSHER_APP_SECRET: ''
  PUSHER_HOST: ''
  PUSHER_PORT: '443'
  PUSHER_SCHEME: 'https'
  PUSHER_APP_CLUSTER: 'mt1'
  VITE_PUSHER_APP_KEY: '${PUSHER_APP_KEY}'
  VITE_PUSHER_HOST: '${PUSHER_HOST}'
  VITE_PUSHER_PORT: '${PUSHER_PORT}'
  VITE_PUSHER_SCHEME: '${PUSHER_SCHEME}'
  VITE_PUSHER_APP_CLUSTER: '${PUSHER_APP_CLUSTER}'
  UNILAB_API_ORIGIN: 'https://api.unilab.edu.br/api'
  
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-regcred
  namespace: app-3s
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2R0aS1yZWdpc3Ryby51bmlsYWIuZWR1LmJyIjp7InVzZXJuYW1lIjoiazhzIiwicGFzc3dvcmQiOiJLOHNAdW5pbGFiMjAyMyIsImVtYWlsIjoiZHRpLWs4c0Bub3JlcGx5LnVuaWxhYi5lZHUuYnIiLCJhdXRoIjoiYXpoek9rczRjMEIxYm1sc1lXSXlNREl6In19fQ==
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-app-3s
  namespace: app-3s
  labels:
    app: app-3s
spec:
  storageClassName: nfs-storage-k8s
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-3s
  namespace: app-3s
automountServiceAccountToken: true

---
apiVersion: v1
kind: Secret
metadata:
 name: app-3s
 namespace: app-3s
 annotations:
   kubernetes.io/service-account.name: app-3s
type: kubernetes.io/service-account-token

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3s
  namespace: app-3s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-3s
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-config: 'secret/data/3s/config'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/data/3s/config" -}}
           export DB_PASSWORD='{{ .Data.data.pg_password }}'
           export DB_USERNAME='{{ .Data.data.pg_user }}'
           export DB_DATABASE_SIGAA='{{ .Data.data.db_database_sigaa }}'
           export DB_USERNAME_SIGAA='{{ .Data.data.db_username_sigaa }}'
           export DB_PASSWORD_SIGAA='{{ .Data.data.db_password_sigaa }}'
           export DB_HOST_SIGAA='{{ .Data.data.db_host_sigaa }}'
          {{- end }}
        vault.hashicorp.com/role: "3s-role"
        vault.hashicorp.com/auth-path: auth/kubernetes/c1
    spec:
      serviceAccountName: "app-3s"
      containers:
      - name: app-3s
        image: dti-registro.unilab.edu.br/unilab/app-3s:latest
        command: ["/bin/bash", "-c", "sudo -s; source /vault/secrets/config; apache2-foreground"]
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        - containerPort: 37389
          name: ssh
        envFrom:
          - configMapRef:
              name: app-3s-config
        volumeMounts:
        - name: tz-america
          mountPath: /etc/localtime
        - name: 3s-uploads
          mountPath: /var/www/html/public/uploads
      volumes:
        - name: tz-america
          hostPath:
            path: /usr/share/zoneinfo/America/Fortaleza
            type: File
        - name: 3s-uploads
          persistentVolumeClaim:
            claimName: pvc-app-3s
      imagePullSecrets:
        - name: harbor-regcred
  selector:
    matchLabels:
        app: app-3s

---
apiVersion: v1
kind: Service
metadata:
  name: app-3s
  namespace: app-3s
  labels:
    app: app-3s
  annotations:
    metallb.universe.tf/address-pool: int-pool
spec:
  selector:
    app: app-3s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 37389
      targetPort: 37389
      name: ssh
  type: LoadBalancer
  loadBalancerIP: 10.130.0.153
  externalTrafficPolicy: Local
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: app-3s
   namespace: app-3s
   annotations:
      haproxy.org/check: enabled
      haproxy.org/forwarded-for: enabled
      haproxy.org/load-balance: roundrobin
      haproxy.org/ssl-redirect: 'true'
      haproxy.org/ssl-redirect-code: '301'
spec:
  rules:
    - host: dti-app-test-c1.unilab.edu.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
               service:
                  name: app-3s
                  port:
                     number: 80
                     