apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app3s-stag
resources:
- ../../base
images:
- name: dti-registro.unilab.edu.br/unilab/app-3s:latest
  newName: dti-registro.unilab.edu.br/unilab/app-3s
  newTag: main
patches:
- path: configmap.yaml
- path: deployment.yaml
- path: service.yaml
- path: ingress.yaml
# - path: hpa.yaml
