## Como usar:
# cd source/
# docker-compose up --build -d
# docker-compose logs -f
# docker exec -it 3s /bin/bash
# docker cp postgres:/var/lib/postgresql/data/postgresql.conf ./docker/postgres/
# docker cp postgres:/var/lib/postgresql/data/pg_hba.conf ./docker/postgres/

## full clean
# docker stop $(docker ps -qa)
# docker rm -f $(docker ps -qa)
# docker rmi -f $(docker images -qa)
# docker volume rm -f $(docker volume ls -q)
# docker network rm $(docker network ls -q)

#Admin Laravel
#Email: teste@user.com
#Password: testpass

version: '3.9'
services:
  ###################################
  # Application
  ################################### 
  # dev
  app-dev:
    build:
      context: ./ 
      dockerfile: ./Dockerfile
      target: dev # dev | production
      cache_from:
        - dti-registro.unilab.edu.br/unilab/app-3s:dev
    image: dti-registro.unilab.edu.br/unilab/app-3s:dev
    container_name: 3s-dev
    restart: always
    user: "root:www-data"
    env_file:
      - .env.dev
    volumes:
      - .:/var/www/3S
      # - .env.dev:/var/www/3S/.env
    ports:
      - "8082:80"
      - "22:22"
    networks:
      - developer
    depends_on:
      - postgresql

  # prod
  app-prod:
    build:
      context: ./ 
      dockerfile: ./Dockerfile
      target: production # dev | production
      cache_from:
        - dti-registro.unilab.edu.br/unilab/app-3s:latest
    image: dti-registro.unilab.edu.br/unilab/app-3s:latest
    container_name: 3s-prod
    restart: always
    user: "root:www-data"
    env_file:
      - .env.prod
    volumes:
      - .:/var/www/3S
      # - .env.dev:/var/www/3S/.env
    ports:
      - "8083:80"
      - "37389:22"
    networks:
      - developer
    depends_on:
      - postgresql

  ###################################
  # PostgreSQL
  ###################################
  postgresql:
    image: postgres:15-bullseye
    container_name: postgres
    # command: ["/wait-for-postgres.sh", "localhost"]
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      # - ./docker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf:rw
      # - ./docker/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf:rw
      - ./db/wait-for-postgres.sh:/wait-for-postgres.sh
      - ./db/init.sql:/mnt/01init.sql
      - ./db/create-postgres-db.sh:/postgres-db.sh
      # - ./db/create-postgres-db.sh:/docker-entrypoint-initdb.d/postgres-db.sh
    networks:
      - developer

  ###################################
  # PgAdmin4 - Tool para PostgreSQL
  ###################################
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - 8090:80
    env_file:
      - .env.dev
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:rw
    networks:
      - developer
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
 developer:
   name: developer
   driver: bridge
   