apiVersion: v1
kind: Secret
metadata:
  name: harbor-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    eyJhdXRocyI6eyJodHRwczovL2R0aS1yZWdpc3Ryby51bmlsYWIuZWR1LmJyIjp7InVzZXJuYW1lIjoiazhzIiwicGFzc3dvcmQiOiJLOHNAdW5pbGFiMjAyMyIsImVtYWlsIjoiZHRpLWs4c0Bub3JlcGx5LnVuaWxhYi5lZHUuYnIiLCJhdXRoIjoiYXpoek9rczRjMEIxYm1sc1lXSXlNREl6In19fQ==
